name: Deploy Hexo to GitHub Pages

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        ref: source
        submodules: true
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build with Hexo
      run: |
        npx hexo clean
        npx hexo generate

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./public
        publish_branch: main
        commit_message: 'Deploy via GitHub Actions: ${{ github.sha }}'
        full_commit_message: 'Deploy Hexo site: ${{ github.sha }} - Built by GitHub Actions'
        force_orphan: true
